import time as t
import calendar
print("\n\n*****************************************************************************************************************************************")
t.sleep(1)
print("*                                      WELCOME TO THE GBV REPORT HUB                                                                    *")
t.sleep(1)
print("*****************************************************************************************************************************************")
print("\n \n")
t.sleep(1)
print("*****************************************************************************************************************************************")
t.sleep(1)
print("*   The GBV report hub is a python program to facilitate the reporting of gender-based violence and any other kind of violence.         *")
t.sleep(1)
print("*****************************************************************************************************************************************")
print("\n \n")
t.sleep(1)
print("                                          **************************************** ")
t.sleep(1)
print("                                          || 1- Report                          ||")
t.sleep(1)
print("                                          || 2- Quit                            ||")
t.sleep(1)
print("                                          || 3- About us                        ||")
t.sleep(1)
print("                                          ****************************************   ")
t.sleep(1)
def mainMenu():
    try:
        t.sleep(1)
        selection = int(input("               ->->->->          If you want to report, type 1, and if not type 2: \n"))
        if selection == 1:
            print("\n \n \n")
            t.sleep(1)
            print("                                  //***************************************\\\\")
            t.sleep(1)
            print("         Welcome again to confirm your willing to report, express your feelng, and trying to help us to address GBV case ")
            t.sleep(1)
            print("                               //*******************************************\\\\")
            t.sleep(1)
            print("_________________________________________________________________________________________________________________________________________________________________")
            print("\n \n \n")
            t.sleep(1)
            Data()
        elif selection == 2:
            print()
            t.sleep(1)
            print("                       __________________//*********************************\\____________________ ")
            t.sleep(1)
            print("                                         Thanks for visiting us. Good Bye!!")
            t.sleep(1)
            print("                    __________________//**************************************\\____________________ ")
        elif selection == 3:
            print()
            t.sleep()
            print("                       __________________//**************************************\\____________________ ")
            t.sleep()
            print("The GBV report hub is a python program to facilitate the reporting of gender-based violence and any other kind of violence. The program will focus on the following case of violence. Interpersonal violence and threats. The program will display different types of options, filter, and make the situation more specific based on the options chosen by the users.") 
            t.sleep()
            print("In order to the desired functionality for our program, we will implement the following features/functions described below:")
            t.sleep()
            print("A function that will introduce the app to the users.")
            t.sleep()
            print("A function that will display options to the users.")
            t.sleep()
            print("A function that gets users' input and filters the output.")
            t.sleep()
            print("And lastly, a function that asks the user to describe his case at least in 30 words.")

            print("")
        else:
            print()
            t.sleep(1)
            print("                       __________________//*********************************\\\\____________________ ")
            t.sleep(1)
            print("                                              Invalid choice: try again!!     ")
            t.sleep(1)
            print("                   __________________//****************************************\\\\____________________ ")
            t.sleep(1)
            print("_________________________________________________________________________________________________________________________________________________________________")
            print("\n \n \n")
            t.sleep(1)
            mainMenu()
    except ValueError:
        print()
        t.sleep(1)
        print("                        __________________//**********************************\\____________________ ")
        t.sleep(1)
        print("                                              Invalid choice: try again!!")
        t.sleep(1)
        print("                    __________________//*****************************************\\____________________ ")
        t.sleep(1)
        print("_________________________________________________________________________________________________________________________________________________________________")
        t.sleep(1)
        mainMenu()


def Data():
    t.sleep(1)
    print("                                            ************************************  ")
    print("                                           ||           NAME SECTION           ||")
    t.sleep(1)
    print("                       __________________//**************************************\\\\____________________ ")
    t.sleep(1)
    n = input("                   ->->->->->->->->     Enter your name or type 1 to return:   \n")
    if n.isdigit() and n == str(1):
        t.sleep(1)
        print("\n_________________________________________________________________________________________________________________________________________________________________")
        t.sleep(1)
        return mainMenu()
    elif n.isdigit() :
        t.sleep(1)
        print("                       __________________//**************************************\\\\____________________ ")
        t.sleep(1)
        print("                                               Invalid name. Retry again: \n")
        t.sleep(1)
        print("_________________________________________________________________________________________________________________________________________________________________")
        print(" \n \n")
        t.sleep(1)
        Data()
    else:
        t.sleep(1)
        print("                                        //**************************************\\ ")
        t.sleep(1)
        print("                                            Welcome again: " + n.upper() + ".        \n")
        t.sleep(1)
        print("                                       //*****************************************\\")
        t.sleep(1)
        print("_________________________________________________________________________________________________________________________________________________________________")
        print("\n \n \n")
        t.sleep(1)
        Age()
    

def Age():
    t.sleep(1)
    print("                                             //*******************************\\")
    t.sleep(1)
    date=input("                   ->->->->       Enter your birth date in (mm dd yyyy) format:  ").split()
    print("\n \n")
    p = int(date[-1])
    s = 2022 - p
    mm,dd,yyyy=list(map(int,date))
    print()
    t.sleep(1)
    print("                                   //****************************************\\\\ ")
    t.sleep(1)
    print("                       |||||--->>  Fun fact: you were born in one " +(calendar.day_name[calendar.weekday(yyyy,mm,dd)]).upper() +" And you are " + str(s) + " years old")
    t.sleep(1)
    print("                                  //******************************************\\\\")
    print("\n \n")
    t.sleep(1)
    print("_________________________________________________________________________________________________________________________________________________________________")

    if s < 18:
        t.sleep(1)
        print("                                           //***********************************\\\\")
        t.sleep(1)
        print("                                        You are below 18, we need your tutor information.")
        t.sleep(1)
        print("                                           //***********************************\\\\")
        t.sleep(1)
        b =input("                                                Enter your tutors name: ")
        if b.isalpha():
            t.sleep(1)
            print("                                           //***********************************\\\\")
            t.sleep(1)
            print('                                                      Tutor name: ' + b)
            Tphone()
        else:
            t.sleep(1)
            print("                                           //***********************************\\\\")
            t.sleep(1)
            print("                                                          Error!!!!")
            print()
            Gender()
    elif s >= 18:
        return Gender()    
    else:
        print()
        t.sleep(1)
        print("                                           //***********************************\\\\")
        t.sleep(1)
        print("                            ->->->->           Only in (mm dd yyyy) format          ")
        t.sleep(1)
        print("                                         //***************************************\\\\ ")
        t.sleep(1)
        print("_________________________________________________________________________________________________________________________________________________________________")
        Age()
def Tphone():
    t.sleep(1)
    print("                                           //***********************************\\\\")
    t.sleep(1)
    n3 = input("                                             Enter your tutor's phone number: \n")
    if n3.isdigit() and len(n3) == 10:
        t.sleep(1)
        print("                                           //***********************************\\\\")
        t.sleep(1)
        print("                                               Tutor phone number is: " + n3 + "\n")
        t.sleep(1)
        print("_________________________________________________________________________________________________________________________________________________________________")
        Gender()
    else:
        t.sleep(1)
        print("                                           //***********************************\\\\")
        t.sleep(1)
        print("                                                  Error. Retry again: \n")
        t.sleep(1)
        print("_________________________________________________________________________________________________________________________________________________________________")
        Tphone()
def Gender():
    t.sleep(1)
    print("                                         //***************************************\\\\")
    t.sleep(1)
    print("                                         ||              1. Male                  || ")
    t.sleep(1)
    print("                                         ||              2. Female                || ")
    t.sleep(1)
    print("                                         //***************************************\\\\ ")

    t.sleep(1)
    print("                 \n\n                          //***********************************\\\\")
    t.sleep(1)
    n2 = int(input("                       ->->->->             What is your gender? \n"))
    if n2 == 1:
        t.sleep(1)
        print("                                           //***********************************\\\\")
        t.sleep(1)
        print("                                  ->->->->->                 MALE. \n")
        t.sleep(1)
        print("_________________________________________________________________________________________________________________________________________________________________")
        print()
        Phonenumber()
    elif n2 == 2:
        t.sleep(1)
        print("                                           //***********************************\\\\")
        t.sleep(1)
        print("                                   ->->->->->                 FEMALE.\n")
        t.sleep(1)
        print("_________________________________________________________________________________________________________________________________________________________________")
        print()
        Phonenumber()
    else:
        t.sleep(1)
        print("                                           //***********************************\\\\")
        t.sleep(1)
        print("                                                  Invalid: enter 1 or 2: \n")
        t.sleep(1)
        print("_________________________________________________________________________________________________________________________________________________________________")
        Gender()

def Phonenumber():
    t.sleep(1)
    print("                                           //***********************************\\\\")
    t.sleep(1)
    n3 = input("                                            Enter your phonr number: \n")
    if len(n3) == 10:
        t.sleep(1)
        print("                                           //***********************************\\\\")
        t.sleep(1)
        print("                                             Your phone number is: " + n3 + "\n")
        t.sleep(1)
        print("_________________________________________________________________________________________________________________________________________________________________")
        Location()
    elif n3.isalpha():
        t.sleep(1)
        print("                                           //***********************************\\\\")
        t.sleep(1)
        print("                                                   Error. Retry again: \n")
        t.sleep(1)
        print("_________________________________________________________________________________________________________________________________________________________________")
        Phonenumber() 
    else:
        t.sleep(1)
        print("                                           //***********************************\\\\")
        t.sleep(1)
        print("                                                  Error. Retry again: \n")
        t.sleep(1)
        print("_________________________________________________________________________________________________________________________________________________________________")
        Phonenumber()

def Location():
    t.sleep(1)
    print("                                           //***********************************\\\\")
    t.sleep(1)
    n4 = str(input("                                          Enter your province:\n"))
    if n4.isalpha():
        t.sleep(1)
        print("                                           //***********************************\\\\")
        t.sleep(1)
        print("                                                     Province: " + n4 + "\n")
        t.sleep(1)
        print("_________________________________________________________________________________________________________________________________________________________________")
        District()
    else:
        t.sleep(1)
        print("                                           //***********************************\\\\")
        t.sleep(1)
        print("                                                   Invalid. Retry again: \n")
        t.sleep(1)
        print("_________________________________________________________________________________________________________________________________________________________________")
        Location()
    
def District():
        t.sleep(1)
        print("                                           //***********************************\\\\")
        t.sleep(1)
        n5 = str(input("                                              Enter your Distric: \n"))
        if n5.isalpha():
            t.sleep(1)
            print("                                           //***********************************\\\\")
            t.sleep(1)
            print("                                                    Your District is: " + n5 + "\n")
            t.sleep(1)
            print("_________________________________________________________________________________________________________________________________________________________________")
            Sector()
        else:
            t.sleep(1)
            print("                                           //***********************************\\\\")
            t.sleep(1)
            print("                                                    Invalid. Retry again:\n")
            t.sleep(1)
            print("_________________________________________________________________________________________________________________________________________________________________")
            District()
    
def Sector():
        t.sleep(1)
        print("                                           //***********************************\\\\")
        t.sleep(1)
        n6 = str(input("                                                Enter your sector:\n"))
        if n6.isalpha():
            t.sleep(1)
            print("                                           //***********************************\\\\")
            t.sleep(1)
            print("                                                  Scetor: " + n6 + "\n")
            t.sleep(1)
            print("_________________________________________________________________________________________________________________________________________________________________")
            Explain()
        else:
            t.sleep(1)
            print("                                           //***********************************\\\\")
            t.sleep(1)
            print("                                                      Invali. Retry again:")
            t.sleep(1)
            print("_________________________________________________________________________________________________________________________________________________________________")
            Sector()

def Explain():
    t.sleep(1)
    print("                                           //***********************************\\\\")
    t.sleep(1)
    n7 = str(input("                               Explain briefly your case in at least 20 words:\n\n\n\n"))
    if len(n7.split()) < 20:
        t.sleep(1)
        print("                                           //***********************************\\\\")
        t.sleep(1)
        print("                                                     At least 20 words!!!")
        t.sleep(1)
        print("_________________________________________________________________________________________________________________________________________________________________")
        Explain()
    else:
        t.sleep(1)
        print(n7)
        t.sleep(1)
        print("_________________________________________________________________________________________________________________________________________________________________")
        CCL()

def CCL():
    t.sleep(1)
    print("                                           //***********************************\\\\")
    t.sleep(1)
    print("                                               Thanks For reporting your case.\n\n")
    t.sleep(1)
    print("                                                        1. Main manu")
    t.sleep(1)
    print("                                                        2. Exit")
    t.sleep(1)
    print("                                           //***********************************\\\\")
    t.sleep(1)
    n8 = int(input("               If you want go back to the main menu, type 1, and if you want to quit, type 2:\n"))
    try:
        if n8 == 1:
            t.sleep(1)
            print("_________________________________________________________________________________________________________________________________________________________________")
            mainMenu()
        elif n8 == 2:
            print()
            t.sleep(1)
            print("                       __________________//*********************************\\____________________ ")
            t.sleep(1)
            print("                                         Thanks for visiting us. Good Bye!!")
            t.sleep(1)
            print("                    __________________//**************************************\\____________________ ")    
        else:
            t.sleep(1)
            print("Please choose 1 or 2")
            t.sleep(1)
            print("_________________________________________________________________________________________________________________________________________________________________")
            CCL()
    except ValueError:
        t.sleep(1)
        print("                                           //***********************************\\\\")
        t.sleep(1)
        print("                                                  Invalid choice. Try agin!!!")
        CCL()





mainMenu()
